console.log("Purge test #6");
import './search/index.js'
import './county-buttons/buttons.js'
import './search/filters.js'
import './charts/relative-percentage-by-100k/index.js'
import './charts/relative-percentage-by-pop/index.js'
import './charts/healthy-places-index/index.js'
import './charts/data-completeness/index.js'
import './charts/social-determinants/index.js'
import './learn-more/index.js'