name: Add Commit Stamp
on:
  push:

jobs:
  testvalidate:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get commit message
        run: |
            echo Commit MSG = ${{ env.commitmsg }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Save Context
        uses: finnp/create-file-action@master
        env:
            FILE_NAME: "deploy-info.txt"
            FILE_DATA: ${{ toJson(github) }}