name: Add Commit Stamp
on:
  pull_request:
    branches: [ master ]

jobs:
  testvalidate:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        env:
          message: ${{ github.event.head_commit.message }}
      - name: get commit message
        run: |
            echo Commit MSG = ${{ env.commitmsg }}